INSERT INTO MODALIDADE(NOME)VALUES('Futebol');
INSERT INTO MODALIDADE(NOME)VALUES('Basquete');
INSERT INTO MODALIDADE(NOME)VALUES('Volei');

INSERT INTO ESTADIO(NOME)VALUES('China');
INSERT INTO ESTADIO(NOME)VALUES('Chininha');
INSERT INTO ESTADIO(NOME)VALUES('Chinão');

INSERT INTO ETAPA(NOME)VALUES('Final');
INSERT INTO ETAPA(NOME)VALUES('Oitavas de Final');
INSERT INTO ETAPA(NOME)VALUES('Quartas de Final');

INSERT INTO FEDERACAO(NOME)VALUES('Brasil');
INSERT INTO FEDERACAO(NOME)VALUES('Argentina');
INSERT INTO FEDERACAO(NOME)VALUES('ChingLing');