INSERT INTO MODALIDADE(NOME)VALUES('Futebol');
INSERT INTO MODALIDADE(NOME)VALUES('Basquete');
INSERT INTO MODALIDADE(NOME)VALUES('Volei');

INSERT INTO ESTADIO(NOME)VALUES('China');
INSERT INTO ESTADIO(NOME)VALUES('ChingLing');
INSERT INTO ESTADIO(NOME)VALUES('ChingNinja');


INSERT INTO ETAPA(ID, NOME)VALUES(1, 'Eliminatórias');
INSERT INTO ETAPA(ID, NOME)VALUES(2, 'Oitavas de Final');
INSERT INTO ETAPA(ID, NOME)VALUES(3, 'Quartas de Final');
INSERT INTO ETAPA(ID, NOME)VALUES(4, 'Final');
INSERT INTO ETAPA(ID, NOME)VALUES(5, 'Semifinal');

INSERT INTO FEDERACAO(NOME)VALUES('Brasil');
INSERT INTO FEDERACAO(NOME)VALUES('Argentina');
INSERT INTO FEDERACAO(NOME)VALUES('Chile');
INSERT INTO FEDERACAO(NOME)VALUES('China');
INSERT INTO FEDERACAO(NOME)VALUES('Japão');
INSERT INTO FEDERACAO(NOME)VALUES('Alemanha');
INSERT INTO FEDERACAO(NOME)VALUES('Belgica');
INSERT INTO FEDERACAO(NOME)VALUES('Africa');

INSERT INTO JOGO(IDFEDERACAO1, IDFEDERACAO2, IDETAPA, IDESTADIO, IDMODALIDADE, DATA_INICIO, DATA_TERMINO)VALUES(1, 1, 1, 1, 1, '2018-02-06 20:27:52', '2018-02-06 20:57:52');