INSERT INTO MODALIDADE(NOME)VALUES('Futebol');
INSERT INTO MODALIDADE(NOME)VALUES('Basquete');
INSERT INTO MODALIDADE(NOME)VALUES('Volei');
INSERT INTO MODALIDADE(NOME)VALUES('Arco e Flecha');
INSERT INTO MODALIDADE(NOME)VALUES('Salto com Vara');
INSERT INTO MODALIDADE(NOME)VALUES('Ginástica');

INSERT INTO ESTADIO(NOME)VALUES('Nacional de Pequim');
INSERT INTO ESTADIO(NOME)VALUES('Olímpico de Guangdong');
INSERT INTO ESTADIO(NOME)VALUES('Olímpico de Nanjing');
INSERT INTO ESTADIO(NOME)VALUES('Yellow Dragon');
INSERT INTO ESTADIO(NOME)VALUES('SportsCentre Yizhong');
INSERT INTO ESTADIO(NOME)VALUES('Popular de Dalian');
INSERT INTO ESTADIO(NOME)VALUES('Multi-uso de Kunming');


INSERT INTO ETAPA(ID, NOME)VALUES(1, 'Eliminatórias');
INSERT INTO ETAPA(ID, NOME)VALUES(2, 'Oitavas de Final');
INSERT INTO ETAPA(ID, NOME)VALUES(3, 'Quartas de Final');
INSERT INTO ETAPA(ID, NOME)VALUES(4, 'Semifinal');
INSERT INTO ETAPA(ID, NOME)VALUES(5, 'Final');

INSERT INTO FEDERACAO(NOME)VALUES('Brasil');
INSERT INTO FEDERACAO(NOME)VALUES('Argentina');
INSERT INTO FEDERACAO(NOME)VALUES('Chile');
INSERT INTO FEDERACAO(NOME)VALUES('China');
INSERT INTO FEDERACAO(NOME)VALUES('Japão');
INSERT INTO FEDERACAO(NOME)VALUES('Alemanha');
INSERT INTO FEDERACAO(NOME)VALUES('Belgica');
INSERT INTO FEDERACAO(NOME)VALUES('Africa');
INSERT INTO FEDERACAO(NOME)VALUES('Bahamas');
INSERT INTO FEDERACAO(NOME)VALUES('Bulgária');
INSERT INTO FEDERACAO(NOME)VALUES('Colômbia');
INSERT INTO FEDERACAO(NOME)VALUES('Costa Rica');
INSERT INTO FEDERACAO(NOME)VALUES('Costa do Marfim');
INSERT INTO FEDERACAO(NOME)VALUES('Croácia');
INSERT INTO FEDERACAO(NOME)VALUES('México');
INSERT INTO FEDERACAO(NOME)VALUES('Peru');