CREATE TABLE IF NOT EXISTS Cars(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100),
  PRICE INT
);

CREATE TABLE IF NOT EXISTS Teste(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  IDCARS INTEGER,
  NAME VARCHAR(100),
  PRICE INT,

  CONSTRAINT FK_TESTE FOREIGN KEY(IDCARS) REFERENCES Cars(ID)
);